name: Update EDT (AI Vision)

on:
  schedule:
    - cron: '0 6 * * *' # Tous les jours à 6h
  workflow_dispatch:      # Permet le lancement manuel

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- NOUVEAU : Installation de Poppler pour lire les PDF comme des images ---
      - name: Install Poppler
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run AI Parser
        env:
          # On injecte la clé secrète qu'on a mise dans les paramètres GitHub
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python edt_parser.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          # On ajoute le calendrier ET le fichier de debug
          git add edt.ics debug.txt
          
          if git diff --staged --quiet; then
            echo "Pas de changement."
          else
            git commit -m "Mise à jour EDT + Debug logs"
            git pull --rebase -Xtheirs origin main
            git push origin main
          fi
