name: Update EDT

on:
  schedule:
    # Tourne tous les jours à 6h00 du matin UTC
    - cron: '0 5 * * *'
  workflow_dispatch: # Permet de lancer manuellement pour tester

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important pour pouvoir push le fichier .ics

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run parser script
        run: python edt_parser.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add edt.ics
          
          # Vérifie s'il y a des changements préparés
          if git diff --staged --quiet; then
            echo "Aucun changement à sauvegarder."
          else
            git commit -m "Mise à jour automatique EDT"
            
            # --- CORRECTION ---
            # On tire les changements. En cas de conflit sur edt.ics, 
            # on force l'utilisation de notre version locale (-Xtheirs)
            git pull --rebase -Xtheirs origin main
            
            git push origin main
          fi
