name: Mise à jour EDT STRI

on:
  schedule:
    - cron: '0 5 * * *' # Tous les jours à 5h00 UTC (6h ou 7h en France)
  workflow_dispatch:      # Permet de lancer manuellement le script

permissions:
  contents: write         # Donne la permission de sauvegarder le fichier .ics

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Lancer la conversion
        run: python scripts/parse_edt.py

      - name: Sauvegarder le fichier .ics (Git Push)
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add edt_stri.ics
          # Ne commit que s'il y a des changements
          git diff --quiet && git diff --staged --quiet || (git commit -m "Mise à jour EDT $(date +'%Y-%m-%d')" && git push)